GET localhost:1998/project/api/projects/1/milestones
Content-Type: application/json

###

POST localhost:1998/project/api/projects/1/milestone
Content-Type: application/json

{
    "name": "두레이 이해하기",
    "startDate": "2023-06-06",
    "endDate": "2023-06-10"
}

###

PUT localhost:1998/project/api/projects/3/milestone/2
Content-Type: application/json

{
    "name": "두레이 이해하기1",
    "startDate": "2023-06-06",
    "endDate": "2023-06-25"
}

###

DELETE localhost:1998/project/api/projects/milestone/1
Content-Type: application/json