POST localhost:1998/project/api/projects HTTP/1.1
Content-Type: application/json

{
  "name": "dooray 미니 프로젝트",
  "description": "미니프로젝트 설명"
}

###
GET localhost:1998/project/api/projects HTTP/1.1

###
GET localhost:1998/project/api/projects/2 HTTP/1.1

###
DELETE localhost:1998/project/api/projects/2 HTTP/1.1

###
PUT localhost:1998/project/api/projects/2 HTTP/1.1
Content-Type: application/json

{
  "name": "업데이트된 dooray 미니 프로젝트",
  "description": "업데이트 된 두레이 미니프로젝트",
  "state": "보관"
}

###
POST localhost:1998/project/api/tags/2 HTTP/1.1
Content-Type: application/json

{
  "name": "tag1",
  "color": "blue"
}
###
GET localhost:1998/project/api/tags HTTP/1.1

###
GET localhost:1998/project/api/tags/1 HTTP/1.1

###
DELETE localhost:1998/project/api/tags/1 HTTP/1.1

###
PUT localhost:1998/project/api/tags/1 HTTP/1.1
Content-Type: application/json

{
  "name": "tag2",
  "color": "red"
}